service: "services.upscaler_service:PhotoUpscalerService"
name: "photo-upscaler-service"
description: "AI-powered photo upscaling service using Real-ESRGAN"

labels:
  owner: bentoml-team
  stage: dev

include:
  - "services/upscaler_service.py"
  - "utils/upscaler/"

python:
  requirements_txt: |
    bentoml[io]>=1.2.0
    realesrgan>=0.3.0
    gfpgan>=1.3.8
    torch>=2.0.0
    torchvision>=0.15.0
    pillow>=9.0.0
    pydantic>=2.0.0
    requests>=2.28.0