# BentoML Configuration for Local Development (macOS)
# This configuration optimizes BentoML for local testing without Docker

api_server:
  # Server configuration
  host: "127.0.0.1"
  port: 3000
  cors:
    enabled: true
    access_control_allow_origins: ["*"]
    access_control_allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    access_control_allow_headers: ["*"]
  
  # Worker configuration for local development
  workers: 1
  timeout: 60
  
  # Logging
  access_log: true
  log_level: "info"

runners:
  # Runner configuration for local testing
  batching:
    enabled: true
    max_batch_size: 100
    max_latency_ms: 1000
  
  # Resource limits for local development
  resources:
    cpu: "1"
    memory: "1Gi"
  
  # Timeout settings
  timeout: 300
  
  logging:
    access:
      enabled: true
      request_content_length: true
      request_content_type: true
      response_content_length: true
      response_content_type: true

# Monitoring and metrics
monitoring:
  enabled: true
  type: "default"
  
tracing:
  enabled: false  # Disable for local testing
  
metrics:
  enabled: true
  namespace: "bentoml_local"

# Logging configuration
logging:
  level: "INFO"
  format: "text"  # Use text format for better readability during development

# Development settings
development:
  enable_swagger_ui: true
  enable_metrics: true
  enable_access_control: false
  reload: true  # Auto-reload on code changes

# Storage configuration for local testing
bentos:
  # Use local filesystem for bento storage
  storage_type: "fs"
  storage_options:
    base_dir: "./bentos"

models:
  # Use local filesystem for model storage
  storage_type: "fs" 
  storage_options:
    base_dir: "./models"